#jsp的视图解析器
spring:
  mvc:
   #设置静态资源的格式
    #static-path-pattern: /**
    static-path-pattern: /static/**
    view:
      suffix: .jsp
      prefix: /jsps/
#开启热部署
  devtools:
    restart:
      enabled: true
#数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/jhsx

server:
#jsp的热部署
  jsp-servlet:
    init-parameters:
      development: true
#修改端口号
  port: 8080
#mybatis的配置
mybatis:
#1.读取mapping映射文件
  mapper-locations: classpath:mapper/*.xml
#2.驼峰命名
  configuration:
    map-underscore-to-camel-case: true
     #3.懒加载
    lazy-loading-enabled: false
#4.起别名
  type-aliases-package: com.buba.boot1806a.pojo
#打印SQL语句
logging:
  level:
    com:
      buba:
        boot1806a:
          dao: debug
#文件上传
User:
  path: F://ideaWorkspace/1806A/beichencarFile
#ueditor文件上传路径的设置
web:
  upload-path: F://ideaWorkspace/1806A/beichencarFile/goodsDetailImg/
